{% set name = "cminpack" %}
{% set version = "1.3.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/devernay/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b891f33ffcfb8b246bb6147a4da6308cdb2386ca42a99892ff9b2e884f8b0386
  patches:
    # Needed because OpenBLAS changes some values in this test
    - 0001-Remove-tlmdif-test-example.patch  # [local_blas_impl == 'openblas']

build:
  skip: true  # [win and vc<14]
  number: 0
  run_exports:
    - {{ pin_subpackage('cminpack', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  # Needed because CMake project is not declared as C
    - cmake
    - ninja
    - m2-dos2unix  # [win]
  host:
    - libblas

test:
  commands:
    - if not exist %LIBRARY_LIB%\\cminpack.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\cminpack.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\\cminpack-1\\cminpack.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\\cminpack-1\\minpack.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\cminpack\\CMinpackConfig.cmake exit 1  # [win]

    - test -a $PREFIX/lib/libcminpack$SHLIB_EXT  # [unix]
    - test -f $PREFIX/include/cminpack-1/cminpack.h  # [unix]
    - test -f $PREFIX/include/cminpack-1/minpack.h  # [unix]
    - test -f $PREFIX/share/cminpack/CMinpackConfig.cmake  # [unix]

about:
  home: http://devernay.free.fr/hacks/cminpack/index.html
  license: MINPACK  # Custom BSD-like
  license_family: BSD
  summary: CMinpack includes software for solving nonlinear equations and nonlinear least squares problems
  license_file: CopyrightMINPACK.txt
  dev_url: https://github.com/devernay/cminpack

extra:
  recipe-maintainers:
    - tadeu
    - jschueller
