travis:
  secure:
    BINSTAR_TOKEN: gjKpYMVIWKFP/mdmTUiu6JnglEiKXZ6p2emZgPwYTEbNmXHqqRgyOiPhJiJ1fn7TVBbTDZXssqQFMEk/sKffavua/UKvS4Et/vfY149jKEP87nCJlPHpISjRCZzn5uGvt+dS87AjEgUNHvjt+KqqBT2x8n4yLa4ILpMsx8UquDhTjy9ERfZBYyiYWvFRKMZBZfIBopMDMG16e7j7/nroLfZabIRqoDp3gvYiIjg0Y7WpL9VJ+cTcQVSLzbIJICs4MeSbp+XqC0xzJt2JuCd6GQSolMQcNBdjKfypQmj+IYbLi0+His83HB6h6uXQEuKBY0Wpq2vUidnVCpgz2njr52gYRZWAC29bGBejERfwv9oNyIMHvp8RYTp/DvEw0pQTcgiT+b0k6pems122K0mRPh/JjBgGtUDImp02SYuGtoyfQ8ATLUUlAn3OFLpdGydHvBYGrJx3bjdWnxp5zwOy00+nlBTA2FA1pGZoPy8RMzxUXZ27dcDbOz/szoHH0tELwdSFATGKQu1Ms4Ly36NyzIRhA1plxZYrj47Tttq6MCNBK8diCC3sFJgKko9j1b0K9kTiGKPzYFa8TYUf+cfezxB8vlVUEnz6XaYw+7WU4yBVX2BjQ9f3KNGxylcfEIiFl6CM4MqirMb2IHEX2xVXZmgsw/gjK4ad2IpkrH7kUvc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
